name: ESP-IDF Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint (clang-tidy via ESP-IDF)
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'push' }}
    env:
      IDF_VERSION: v5.5
      ESP_IDF_EXPORT_DEBUG: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Cache ESP-IDF & tools
        id: idf-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif
            ${{ github.workspace }}/.esp/tools
            ${{ github.workspace }}/.esp/idf
          key: ${{ runner.os }}-espidf-${{ env.IDF_VERSION }}-${{ hashFiles('**/CMakeLists.txt', '**_
