name: ESP-IDF Build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  lint:
    name: Lint (clang-tidy via ESP-IDF)
    runs-on: ubuntu-latest
    # Non-blocking on pushes, blocking on PRs
    continue-on-error: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.5"

      - name: Install ESP-IDF tools (incl. esp-clang)
        shell: bash
        run: |
          set -euo pipefail
          # Install all required tools (core + python deps)
          python3 "$IDF_PATH/tools/idf_tools.py" install
          # Install esp-clang for clang-tidy
          python3 "$IDF_PATH/tools/idf_tools.py" install esp-clang
          # Activate the ESP-IDF environment now that tools are in place
          . "$IDF_PATH/export.sh"
          idf.py --version

      - name: Run clang-tidy
        shell: bash
        env:
          IDF_TOOLCHAIN: clang
        run: |
          set -e
          . "$IDF_PATH/export.sh"
          idf.py set-target esp32s3
          idf.py clang-check \
          --run-clang-tidy-options "-header-filter='(^|.*/)(main|components)/' \
                                    --exclude-header-filter='(^|.*/)(esp-idf|\\.esp|build)/'"
          # Optional HTML report
          python -m pip install codereport || true
          idf.py clang-html-report || true

      - name: Upload lint artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: esp-idf-clang-tidy-report
          path: |
            warnings.txt
            html_report/

  build:
    name: Build (gated by lint on PRs)
    runs-on: ubuntu-latest
    needs: lint
    # Non-blocking on pushes, blocking on PRs
    continue-on-error: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.5"

      - name: Install ESP-IDF tools
        shell: bash
        run: |
          set -euo pipefail
          # Install required toolchains
          python3 "$IDF_PATH/tools/idf_tools.py" install
          # Activate environment
          . "$IDF_PATH/export.sh"
          idf.py --version

      - name: Build
        shell: bash
        run: |
          set -e
          . "$IDF_PATH/export.sh"
          idf.py set-target esp32s3
          idf.py build
