name: ESP-IDF Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint (clang-tidy via ESP-IDF)
    runs-on: ubuntu-latest
    # Non-blocking on pushes, blocking on PRs
    continue-on-error: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.5"

      - name: Install esp-clang toolchain
        shell: bash
        run: |
          set -e
          # Load ESP-IDF env (activates venv, sets IDF_PATH/PATH, etc.)
          . "$IDF_PATH/export.sh"
          # Optional: keep pip current inside the ESP-IDF venv
          python -m pip install --upgrade pip
          # Install esp-clang using the explicit path to idf_tools.py
          python "$IDF_PATH/tools/idf_tools.py" install esp-clang
          # Re-export so the newly installed toolchain is on PATH
          . "$IDF_PATH/export.sh"
          # Sanity check
          idf.py --version

      - name: Run clang-tidy
        shell: bash
        env:
          IDF_TOOLCHAIN: clang
        run: |
          set -e
          . "$IDF_PATH/export.sh"
          idf.py set-target esp32s3
          idf.py clang-check
          # Optional HTML report
          python -m pip install codereport || true
          idf.py clang-html-report || true

      - name: Upload lint artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: esp-idf-clang-tidy-report
          path: |
            warnings.txt
            html_report/

  build:
    name: Build (gated by lint on PRs)
    runs-on: ubuntu-latest
    needs: lint
    # Non-blocking on pushes, blocking on PRs
    continue-on-error: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.5"

      - name: Build
        shell: bash
        run: |
          set -e
          . "$IDF_PATH/export.sh"
          idf.py set-target esp32s3
          idf.py build
