name: ESP-IDF Build

on: { push: { branches: [ main ] }, pull_request: { branches: [ main ] } }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ESP-IDF Build
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.5"
      - name: Build
        run: |
          idf.py set-target esp32s3
          idf.py build
