name: ESP-IDF Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint (clang-tidy via ESP-IDF)
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'push' }}
    env:
      IDF_VERSION: v5.5
      ESP_IDF_EXPORT_DEBUG: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Cache ESP-IDF & tools
        id: idf-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif
            ${{ github.workspace }}/.esp/tools
            ${{ github.workspace }}/.esp/idf
          key: "${{ format('{0}-espidf-{1}-{2}', runner.os, env.IDF_VERSION, hashFiles('**/CMakeLists.txt','**/idf_component.yml','idf_component.yml','managed_components/**','**/requirements.txt','requirements.txt','sdkconfig')) }}"
          restore-keys: |
            ${{ runner.os }}-espidf-${{ env.IDF_VERSION }}-

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: ${{ env.IDF_VERSION }}
          path: ${{ github.workspace }}/.esp/idf
          tools-path: ${{ github.workspace }}/.esp/tools

      # Install tools BEFORE export (idempotent; fixes esp-rom-elfs missing)
      - name: Bootstrap ESP-IDF tools
        shell: bash
        run: |
          set -euxo pipefail
          python3 "$IDF_PATH/too_
