name: ESP-IDF Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint (clang-tidy via ESP-IDF)
    runs-on: ubuntu-latest
    # Non-blocking on pushes, blocking on PRs
    continue-on-error: ${{ github.event_name == 'push' }}
    env:
      IDF_VERSION: v5.5
      ESP_TOOLS_PATH: ${{ runner.temp }}/esp-tools
      ESP_IDF_PATH: ${{ runner.temp }}/esp-idf
      ESP_IDF_EXPORT_DEBUG: "1"   # more verbose export logs

    steps:
      - uses: actions/checkout@v4

      - name: Cache ESP-IDF & tools
        id: idf-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif
            ${{ env.ESP_TOOLS_PATH }}
            ${{ env.ESP_IDF_PATH }}
          key: ${{ runner.os }}-espidf-${{ env.IDF_VERSION }}-${{ hashFiles('**/CMakeLists.txt', '**/idf_component.yml', 'idf_component.yml', 'managed_components/**', '**/requirements.txt', 'requirements.txt', 'sdkconfig') }}
          restore-keys: |
            ${{ runner.os }}-espidf-${{ env.IDF_VERSION }}-

      - name: Debug info (before setup)
        run: |
          set -euxo pipefail
          echo "Cache hit: ${{ steps.idf-cache.outputs.cache-hit }}"
          python3 --version
          echo "HOME=$HOME"
          echo "ESP_IDF_PATH=$ESP_IDF_PATH"
          echo "ESP_TOOLS_PATH=$ESP_TOOLS_PATH"
          ls -la "$HOME" || true
          ls -la "$ESP_IDF_PATH" || true
          ls -la "$ESP_TOOLS_PATH" || true

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: ${{ env.IDF_VERSION }}
          path: ${{ env.ESP_IDF_PATH }}
          tools-path: ${{ env.ESP_TOOLS_PATH }}
          # The action installs required tools; no manual idf_tools.py install needed

      - name: Verify environment
        run: |
          set -euxo pipefail
          . "$IDF_PATH/export.sh"
          which python
          python -m pip --version
          idf.py --version
          python -c "import sys; print('venv:', sys.prefix)"

      - name: Install esp-clang (for clang-tidy)
        run: |
          set -euxo pipefail
          # Use idf_tools.py explicitly; action already set up IDF_PATH
          python3 "$IDF_PATH/tools/idf_tools.py" install esp-clang
          . "$IDF_PATH/export.sh"
          # Quick sanity: show clang-tidy path if present
          command -v clang-tidy || true

      - name: Run clang-tidy
        env:
          IDF_TOOLCHAIN: clang
        run: |
          set -euxo pipefail
          . "$IDF_PATH/export.sh"
          idf.py set-target esp32s3
          idf.py clang-check
          python -m pip install codereport || true
          idf.py clang-html-report || true

      - name: Upload lint artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: esp-idf-clang-tidy-report
          path: |
            warnings.txt
            html_report/

  build:
    name: Build (gated by lint on PRs)
    runs-on: ubuntu-latest
    needs: lint
    # Non-blocking on pushes, blocking on PRs
    continue-on-error: ${{ github.event_name == 'push' }}
    env:
      IDF_VERSION: v5.5
      ESP_TOOLS_PATH: ${{ runner.temp }}/esp-tools
      ESP_IDF_PATH: ${{ runner.temp }}/esp-idf
      ESP_IDF_EXPORT_DEBUG: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Restore ESP-IDF & tools cache
        id: idf-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif
            ${{ env.ESP_TOOLS_PATH }}
            ${{ env.ESP_IDF_PATH }}
          key: ${{ runner.os }}-espidf-${{ env.IDF_VERSION }}-${{ hashFiles('**/CMakeLists.txt', '**/idf_component.yml', 'idf_component.yml', 'managed_components/**', '**/requirements.txt', 'requirements.txt', 'sdkconfig') }}
          restore-keys: |
            ${{ runner.os }}-espidf-${{ env.IDF_VERSION }}-

      - name: Debug info (before setup)
        run: |
          set -euxo pipefail
          echo "Cache hit: ${{ steps.idf-cache.outputs.cache-hit }}"
          python3 --version
          echo "ESP_IDF_PATH=$ESP_IDF_PATH"
          echo "ESP_TOOLS_PATH=$ESP_TOOLS_PATH"
          ls -la "$ESP_IDF_PATH" || true
          ls -la "$ESP_TOOLS_PATH" || true

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: ${{ env.IDF_VERSION }}
          path: ${{ env.ESP_IDF_PATH }}
          tools-path: ${{ env.ESP_TOOLS_PATH }}

      - name: Verify environment
        run: |
          set -euxo pipefail
          . "$IDF_PATH/export.sh"
          which python
          python -m pip --version
          idf.py --version

      - name: Build
        run: |
          set -euxo pipefail
          . "$IDF_PATH/export.sh"
          idf.py set-target esp32s3
          idf.py build
