name: ESP-IDF Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint (clang-tidy via ESP-IDF)
    runs-on: ubuntu-latest
    # Non-blocking on pushes, blocking on PRs
    continue-on-error: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.5"

      - name: Install esp-clang toolchain
        shell: bash
        run: |
          python -m pip install --upgrade pip
          idf_tools.py install esp-clang
          . "$IDF_PATH/export.sh"

      - name: Run clang-tidy
        shell: bash
        env:
          IDF_TOOLCHAIN: clang
        run: |
          set -e
          . "$IDF_PATH/export.sh"
          idf.py set-target esp32s3
          idf.py clang-check
          # Optional HTML report; ignore if helper isn't available
          python -m pip install codereport || true
          idf.py clang-html-report || true

      - name: Upload lint artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: esp-idf-clang-tidy-report
          path: |
            warnings.txt
            html_report/

  build:
    name: Build (gated by lint on PRs)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: ESP-IDF Setup
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.5"

      - name: Build
        shell: bash
        run: |
          . "$IDF_PATH/export.sh"
          idf.py set-target esp32s3
          idf.py build
